package net.nibr.hadwrap.spark.rdd

/**
 * Created by Jason Calvert on 5/30/14.
 */

import org.apache.spark.SparkContext
import org.apache.spark.rdd.RDD

object FileNamesToRDD {

  /**
   * @param sc the SparkContext
   * @param fileList an array of strings each representing a maprfs file path
   * @return returns the union-ed  RDDs generated by combining all for the RDDs for the files
   */
  def RDDFromStringList(sc: SparkContext, fileList: Array[String]) : RDD[String] = {
    RDDMerge.mergeRDDs(sc,RDDsFromList(sc,fileList))
  }

  def RDDsFromList(sc: SparkContext, fileList : Array[String]) : Array[RDD[String]] = {
    fileList.map( s => sc.textFile(s))
  }


}
